apiVersion: v1
kind: List
items:

# When we have an orchestrating operator, it will do this
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: system:openshift:operator:csr-approver
  roleRef:
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    namespace: openshift-csr-approver
    name: openshift-csr-approver-operator
