apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: Namespace
  metadata:
    name: openshift-csr-approver

- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: csrapproveroperatorconfigs.csrapprover.config.openshift.io
  spec:
    scope: Cluster
    group: csrapprover.config.openshift.io
    version: v1alpha1
    names:
      kind: CSRApproverOperatorConfig
      plural: csrapproveroperatorconfigs
      singular: csrapproveroperatorconfig
    subresources:
      status: {}

- apiVersion: v1
  kind: ConfigMap
  metadata:
    namespace: openshift-csr-approver
    name: openshift-csr-approver-operator-config
  data:
    operator-config.yaml: |
      apiVersion: operator.openshift.io/v1alpha1
      kind: GenericOperatorConfig

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    namespace: openshift-csr-approver
    name: openshift-csr-approver-operator
    labels:
      app: openshift-csr-approver-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: openshift-csr-approver-operator
    template:
      metadata:
        name: openshift-csr-approver-operator
        labels:
          app: openshift-csr-approver-operator
      spec:
        serviceAccountName: openshift-csr-approver-operator
        containers:
        - name: operator
          image: openshift/origin-csr-approver:latest
          imagePullPolicy: Always
          command: ["csr-approver", "operator"]
          args:
          - "--config=/var/run/configmaps/config/operator-config.yaml"
          - "-v=4"
          volumeMounts:
          - mountPath: /var/run/configmaps/config
            name: config
        volumes:
        - name: serving-cert
          secret:
            defaultMode: 400
            secretName: openshift-csr-approver-operator-serving-cert
            optional: true
        - name: config
          configMap:
            defaultMode: 440
            name: openshift-csr-approver-operator-config

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    namespace: openshift-csr-approver
    name: openshift-csr-approver-operator
    labels:
      app: openshift-csr-approver-operator

- apiVersion: csrapprover.config.openshift.io/v1alpha1
  kind: CSRApproverOperatorConfig
  metadata:
    name: instance
  spec:
    managementState: Managed
    imagePullSpec: openshift/origin-csr-approver:latest
    version: 3.11.0
    logging:
      level: 4
    replicas: 1
