/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/mrogers950/csr-approver-operator/pkg/apis/csrapprover.config.openshift.io/v1alpha1"
	scheme "github.com/mrogers950/csr-approver-operator/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CSRApproverOperatorConfigsGetter has a method to return a CSRApproverOperatorConfigInterface.
// A group's client should implement this interface.
type CSRApproverOperatorConfigsGetter interface {
	CSRApproverOperatorConfigs() CSRApproverOperatorConfigInterface
}

// CSRApproverOperatorConfigInterface has methods to work with CSRApproverOperatorConfig resources.
type CSRApproverOperatorConfigInterface interface {
	Create(*v1alpha1.CSRApproverOperatorConfig) (*v1alpha1.CSRApproverOperatorConfig, error)
	Update(*v1alpha1.CSRApproverOperatorConfig) (*v1alpha1.CSRApproverOperatorConfig, error)
	UpdateStatus(*v1alpha1.CSRApproverOperatorConfig) (*v1alpha1.CSRApproverOperatorConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.CSRApproverOperatorConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.CSRApproverOperatorConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CSRApproverOperatorConfig, err error)
	CSRApproverOperatorConfigExpansion
}

// cSRApproverOperatorConfigs implements CSRApproverOperatorConfigInterface
type cSRApproverOperatorConfigs struct {
	client rest.Interface
}

// newCSRApproverOperatorConfigs returns a CSRApproverOperatorConfigs
func newCSRApproverOperatorConfigs(c *CsrapproverV1alpha1Client) *cSRApproverOperatorConfigs {
	return &cSRApproverOperatorConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the cSRApproverOperatorConfig, and returns the corresponding cSRApproverOperatorConfig object, and an error if there is any.
func (c *cSRApproverOperatorConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	result = &v1alpha1.CSRApproverOperatorConfig{}
	err = c.client.Get().
		Resource("csrapproveroperatorconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CSRApproverOperatorConfigs that match those selectors.
func (c *cSRApproverOperatorConfigs) List(opts v1.ListOptions) (result *v1alpha1.CSRApproverOperatorConfigList, err error) {
	result = &v1alpha1.CSRApproverOperatorConfigList{}
	err = c.client.Get().
		Resource("csrapproveroperatorconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested cSRApproverOperatorConfigs.
func (c *cSRApproverOperatorConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("csrapproveroperatorconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a cSRApproverOperatorConfig and creates it.  Returns the server's representation of the cSRApproverOperatorConfig, and an error, if there is any.
func (c *cSRApproverOperatorConfigs) Create(cSRApproverOperatorConfig *v1alpha1.CSRApproverOperatorConfig) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	result = &v1alpha1.CSRApproverOperatorConfig{}
	err = c.client.Post().
		Resource("csrapproveroperatorconfigs").
		Body(cSRApproverOperatorConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a cSRApproverOperatorConfig and updates it. Returns the server's representation of the cSRApproverOperatorConfig, and an error, if there is any.
func (c *cSRApproverOperatorConfigs) Update(cSRApproverOperatorConfig *v1alpha1.CSRApproverOperatorConfig) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	result = &v1alpha1.CSRApproverOperatorConfig{}
	err = c.client.Put().
		Resource("csrapproveroperatorconfigs").
		Name(cSRApproverOperatorConfig.Name).
		Body(cSRApproverOperatorConfig).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *cSRApproverOperatorConfigs) UpdateStatus(cSRApproverOperatorConfig *v1alpha1.CSRApproverOperatorConfig) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	result = &v1alpha1.CSRApproverOperatorConfig{}
	err = c.client.Put().
		Resource("csrapproveroperatorconfigs").
		Name(cSRApproverOperatorConfig.Name).
		SubResource("status").
		Body(cSRApproverOperatorConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the cSRApproverOperatorConfig and deletes it. Returns an error if one occurs.
func (c *cSRApproverOperatorConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("csrapproveroperatorconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *cSRApproverOperatorConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("csrapproveroperatorconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched cSRApproverOperatorConfig.
func (c *cSRApproverOperatorConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	result = &v1alpha1.CSRApproverOperatorConfig{}
	err = c.client.Patch(pt).
		Resource("csrapproveroperatorconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
