/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mrogers950/csr-approver-operator/pkg/apis/csrapprover.config.openshift.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCSRApproverOperatorConfigs implements CSRApproverOperatorConfigInterface
type FakeCSRApproverOperatorConfigs struct {
	Fake *FakeCsrapproverV1alpha1
}

var csrapproveroperatorconfigsResource = schema.GroupVersionResource{Group: "csrapprover.config.openshift.io", Version: "v1alpha1", Resource: "csrapproveroperatorconfigs"}

var csrapproveroperatorconfigsKind = schema.GroupVersionKind{Group: "csrapprover.config.openshift.io", Version: "v1alpha1", Kind: "CSRApproverOperatorConfig"}

// Get takes name of the cSRApproverOperatorConfig, and returns the corresponding cSRApproverOperatorConfig object, and an error if there is any.
func (c *FakeCSRApproverOperatorConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(csrapproveroperatorconfigsResource, name), &v1alpha1.CSRApproverOperatorConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSRApproverOperatorConfig), err
}

// List takes label and field selectors, and returns the list of CSRApproverOperatorConfigs that match those selectors.
func (c *FakeCSRApproverOperatorConfigs) List(opts v1.ListOptions) (result *v1alpha1.CSRApproverOperatorConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(csrapproveroperatorconfigsResource, csrapproveroperatorconfigsKind, opts), &v1alpha1.CSRApproverOperatorConfigList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CSRApproverOperatorConfigList{ListMeta: obj.(*v1alpha1.CSRApproverOperatorConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.CSRApproverOperatorConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cSRApproverOperatorConfigs.
func (c *FakeCSRApproverOperatorConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(csrapproveroperatorconfigsResource, opts))
}

// Create takes the representation of a cSRApproverOperatorConfig and creates it.  Returns the server's representation of the cSRApproverOperatorConfig, and an error, if there is any.
func (c *FakeCSRApproverOperatorConfigs) Create(cSRApproverOperatorConfig *v1alpha1.CSRApproverOperatorConfig) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(csrapproveroperatorconfigsResource, cSRApproverOperatorConfig), &v1alpha1.CSRApproverOperatorConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSRApproverOperatorConfig), err
}

// Update takes the representation of a cSRApproverOperatorConfig and updates it. Returns the server's representation of the cSRApproverOperatorConfig, and an error, if there is any.
func (c *FakeCSRApproverOperatorConfigs) Update(cSRApproverOperatorConfig *v1alpha1.CSRApproverOperatorConfig) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(csrapproveroperatorconfigsResource, cSRApproverOperatorConfig), &v1alpha1.CSRApproverOperatorConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSRApproverOperatorConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCSRApproverOperatorConfigs) UpdateStatus(cSRApproverOperatorConfig *v1alpha1.CSRApproverOperatorConfig) (*v1alpha1.CSRApproverOperatorConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(csrapproveroperatorconfigsResource, "status", cSRApproverOperatorConfig), &v1alpha1.CSRApproverOperatorConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSRApproverOperatorConfig), err
}

// Delete takes name of the cSRApproverOperatorConfig and deletes it. Returns an error if one occurs.
func (c *FakeCSRApproverOperatorConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(csrapproveroperatorconfigsResource, name), &v1alpha1.CSRApproverOperatorConfig{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCSRApproverOperatorConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(csrapproveroperatorconfigsResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CSRApproverOperatorConfigList{})
	return err
}

// Patch applies the patch and returns the patched cSRApproverOperatorConfig.
func (c *FakeCSRApproverOperatorConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CSRApproverOperatorConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(csrapproveroperatorconfigsResource, name, pt, data, subresources...), &v1alpha1.CSRApproverOperatorConfig{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CSRApproverOperatorConfig), err
}
