// Code generated by go-bindata.
// sources:
// bindata/v3.11.0/csr-approver-controller/clusterrole.yaml
// bindata/v3.11.0/csr-approver-controller/clusterrolebinding.yaml
// bindata/v3.11.0/csr-approver-controller/cm.yaml
// bindata/v3.11.0/csr-approver-controller/defaultconfig.yaml
// bindata/v3.11.0/csr-approver-controller/deployment.yaml
// bindata/v3.11.0/csr-approver-controller/ns.yaml
// bindata/v3.11.0/csr-approver-controller/sa.yaml
// bindata/v3.11.0/csr-approver-controller/svc.yaml
// DO NOT EDIT!

package v311_00_assets

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)
type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _v3110CsrApproverControllerClusterroleYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:openshift:controller:csr-approver
rules:
# TODO: change to allow just CSR modification
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - update
  - patch
`)

func v3110CsrApproverControllerClusterroleYamlBytes() ([]byte, error) {
	return _v3110CsrApproverControllerClusterroleYaml, nil
}

func v3110CsrApproverControllerClusterroleYaml() (*asset, error) {
	bytes, err := v3110CsrApproverControllerClusterroleYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v3.11.0/csr-approver-controller/clusterrole.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v3110CsrApproverControllerClusterrolebindingYaml = []byte(`apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:controller:csr-approver
roleRef:
  kind: ClusterRole
  name: system:openshift:controller:csr-approver
subjects:
- kind: ServiceAccount
  namespace: openshift-csr-approver
  name: csr-approver-sa
`)

func v3110CsrApproverControllerClusterrolebindingYamlBytes() ([]byte, error) {
	return _v3110CsrApproverControllerClusterrolebindingYaml, nil
}

func v3110CsrApproverControllerClusterrolebindingYaml() (*asset, error) {
	bytes, err := v3110CsrApproverControllerClusterrolebindingYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v3.11.0/csr-approver-controller/clusterrolebinding.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v3110CsrApproverControllerCmYaml = []byte(`apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-csr-approver
  name: csr-approver-config
data:
  controller-config.yaml:
`)

func v3110CsrApproverControllerCmYamlBytes() ([]byte, error) {
	return _v3110CsrApproverControllerCmYaml, nil
}

func v3110CsrApproverControllerCmYaml() (*asset, error) {
	bytes, err := v3110CsrApproverControllerCmYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v3.11.0/csr-approver-controller/cm.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v3110CsrApproverControllerDefaultconfigYaml = []byte(`apiVersion: csrapprover.config.openshift.io/v1alpha1
kind: CSRApproverConfig
signer:
  certFile: /var/run/secrets/signing-key/tls.crt
  keyFile: /var/run/secrets/signing-key/tls.key
`)

func v3110CsrApproverControllerDefaultconfigYamlBytes() ([]byte, error) {
	return _v3110CsrApproverControllerDefaultconfigYaml, nil
}

func v3110CsrApproverControllerDefaultconfigYaml() (*asset, error) {
	bytes, err := v3110CsrApproverControllerDefaultconfigYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v3.11.0/csr-approver-controller/defaultconfig.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v3110CsrApproverControllerDeploymentYaml = []byte(`apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-csr-approver
  name: csr-approver
  labels:
    app: openshift-csr-approver
    csr-approver: "true"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: openshift-csr-approver
      csr-approver: "true"
  template:
    metadata:
      name: csr-approver
      labels:
        app: openshift-csr-approver
        csr-approver: "true"
    spec:
      serviceAccountName: csr-approver-sa
      containers:
      - name: csr-approver-controller
        image: ${IMAGE}
        imagePullPolicy: Always
        command: ["csr-approver", "csr-approver"]
        args:
        - "--config=/var/run/configmaps/config/controller-config.yaml"
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      volumes:
      - name: serving-cert
        secret:
          secretName: csr-approver-serving-cert
          optional: true
      - name: config
        configMap:
          name: csr-approver-config
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: Exists
`)

func v3110CsrApproverControllerDeploymentYamlBytes() ([]byte, error) {
	return _v3110CsrApproverControllerDeploymentYaml, nil
}

func v3110CsrApproverControllerDeploymentYaml() (*asset, error) {
	bytes, err := v3110CsrApproverControllerDeploymentYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v3.11.0/csr-approver-controller/deployment.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v3110CsrApproverControllerNsYaml = []byte(`apiVersion: v1
kind: Namespace
metadata:
  name: openshift-csr-approver
#  labels:
#    openshift.io/run-level: "1"`)

func v3110CsrApproverControllerNsYamlBytes() ([]byte, error) {
	return _v3110CsrApproverControllerNsYaml, nil
}

func v3110CsrApproverControllerNsYaml() (*asset, error) {
	bytes, err := v3110CsrApproverControllerNsYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v3.11.0/csr-approver-controller/ns.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v3110CsrApproverControllerSaYaml = []byte(`apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-csr-approver
  name: csr-approver-sa
`)

func v3110CsrApproverControllerSaYamlBytes() ([]byte, error) {
	return _v3110CsrApproverControllerSaYaml, nil
}

func v3110CsrApproverControllerSaYaml() (*asset, error) {
	bytes, err := v3110CsrApproverControllerSaYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v3.11.0/csr-approver-controller/sa.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _v3110CsrApproverControllerSvcYaml = []byte(`apiVersion: v1
kind: Service
metadata:
  namespace: openshift-csr-approver
  name: csr-approver
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: csr-approver-serving-cert
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    csr-approver: "true"
  ports:
  - name: https
    port: 443
    targetPort: 8443
`)

func v3110CsrApproverControllerSvcYamlBytes() ([]byte, error) {
	return _v3110CsrApproverControllerSvcYaml, nil
}

func v3110CsrApproverControllerSvcYaml() (*asset, error) {
	bytes, err := v3110CsrApproverControllerSvcYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "v3.11.0/csr-approver-controller/svc.yaml", size: 0, mode: os.FileMode(0), modTime: time.Unix(0, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"v3.11.0/csr-approver-controller/clusterrole.yaml": v3110CsrApproverControllerClusterroleYaml,
	"v3.11.0/csr-approver-controller/clusterrolebinding.yaml": v3110CsrApproverControllerClusterrolebindingYaml,
	"v3.11.0/csr-approver-controller/cm.yaml": v3110CsrApproverControllerCmYaml,
	"v3.11.0/csr-approver-controller/defaultconfig.yaml": v3110CsrApproverControllerDefaultconfigYaml,
	"v3.11.0/csr-approver-controller/deployment.yaml": v3110CsrApproverControllerDeploymentYaml,
	"v3.11.0/csr-approver-controller/ns.yaml": v3110CsrApproverControllerNsYaml,
	"v3.11.0/csr-approver-controller/sa.yaml": v3110CsrApproverControllerSaYaml,
	"v3.11.0/csr-approver-controller/svc.yaml": v3110CsrApproverControllerSvcYaml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"v3.11.0": &bintree{nil, map[string]*bintree{
		"csr-approver-controller": &bintree{nil, map[string]*bintree{
			"clusterrole.yaml": &bintree{v3110CsrApproverControllerClusterroleYaml, map[string]*bintree{}},
			"clusterrolebinding.yaml": &bintree{v3110CsrApproverControllerClusterrolebindingYaml, map[string]*bintree{}},
			"cm.yaml": &bintree{v3110CsrApproverControllerCmYaml, map[string]*bintree{}},
			"defaultconfig.yaml": &bintree{v3110CsrApproverControllerDefaultconfigYaml, map[string]*bintree{}},
			"deployment.yaml": &bintree{v3110CsrApproverControllerDeploymentYaml, map[string]*bintree{}},
			"ns.yaml": &bintree{v3110CsrApproverControllerNsYaml, map[string]*bintree{}},
			"sa.yaml": &bintree{v3110CsrApproverControllerSaYaml, map[string]*bintree{}},
			"svc.yaml": &bintree{v3110CsrApproverControllerSvcYaml, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

