apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:controller:csr-approver
roleRef:
  kind: ClusterRole
  name: system:openshift:controller:csr-approver
subjects:
- kind: ServiceAccount
  namespace: openshift-csr-approver
  name: csr-approver-sa
