apiVersion: v1
kind: Service
metadata:
  namespace: openshift-service-cert-signer
  name: service-serving-cert-signer
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: service-serving-cert-signer-serving-cert
    prometheus.io/scrape: "true"
    prometheus.io/scheme: https
spec:
  selector:
    service-serving-cert-signer: "true"
  ports:
  - name: https
    port: 443
    targetPort: 8443
